### PR TITLE
Add word2vec model 

### PR DESCRIPTION
**Pull request by treblenalto**
added pickled word2vec model trained with epoch 1500

### CODE REVIEW

**Comment by treblenalto** [comment]
- added: 
  - pretest_w2v : word2vec model file trained with 1500 epoch
- revised:
  - pretest_tit2vec.ipynb : revised pd.to_csv index to False

**Comment by treblenalto** [comment]
Re-ran word2vec and title2vec code with vector dimension 10
- pretest_w2v.ipynb --> retrained word2vec model (size 10)
- pretest_tit2vec.ipynb --> recalculated title vector (size 10)

cosine vectorization was unsuccessful... (memory error)

**Comment by YHaJung** [comment]
확인했습니다!

**Review by YHaJung — APPROVED** [review]
확인했습니다

**Pull request merged**
